CREATE TABLE university (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    code            VARCHAR(32),
    country         VARCHAR(64),
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(128),
    updated_by      VARCHAR(128),
    version         INT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX uk_university_name ON university (name);
CREATE UNIQUE INDEX uk_university_code ON university (code);

CREATE TABLE professor (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    university_id        BIGINT NOT NULL,
    first_name           VARCHAR(128) NOT NULL,
    last_name            VARCHAR(128) NOT NULL,
    email                VARCHAR(255) NOT NULL,
    department           VARCHAR(128),
    research_areas       VARCHAR(512),
    seniority            VARCHAR(32) NOT NULL DEFAULT 'JUNIOR',
    max_active_reviews   INT NOT NULL DEFAULT 5,
    active_review_count  INT NOT NULL DEFAULT 0,
    deleted              BOOLEAN NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by           VARCHAR(128),
    updated_by           VARCHAR(128),
    version              INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_professor_university FOREIGN KEY (university_id) REFERENCES university (id)
);

CREATE UNIQUE INDEX uk_professor_email ON professor (email);
CREATE INDEX idx_professor_university_dept ON professor (university_id, department);

CREATE TABLE student (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    university_id   BIGINT NOT NULL,
    first_name      VARCHAR(128) NOT NULL,
    last_name       VARCHAR(128) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    department      VARCHAR(128),
    year_level      INT,
    interests       VARCHAR(512),
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(128),
    updated_by      VARCHAR(128),
    version         INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_student_university FOREIGN KEY (university_id) REFERENCES university (id)
);

CREATE UNIQUE INDEX uk_student_email ON student (email);
CREATE INDEX idx_student_university_dept ON student (university_id, department);

CREATE TABLE student_review (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      BIGINT NOT NULL,
    professor_id    BIGINT NOT NULL,
    university_id   BIGINT NOT NULL,
    title           VARCHAR(255) NOT NULL,
    body            VARCHAR(4000),
    rating          INT,
    status          VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    submitted_at    TIMESTAMP WITH TIME ZONE,
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(128),
    updated_by      VARCHAR(128),
    version         INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_review_student FOREIGN KEY (student_id) REFERENCES student (id),
    CONSTRAINT fk_review_professor FOREIGN KEY (professor_id) REFERENCES professor (id),
    CONSTRAINT fk_review_university FOREIGN KEY (university_id) REFERENCES university (id)
);

CREATE INDEX idx_student_review_student ON student_review (student_id);
CREATE INDEX idx_student_review_professor ON student_review (professor_id);

CREATE TABLE review_assignment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      BIGINT NOT NULL,
    professor_id    BIGINT NOT NULL,
    university_id   BIGINT NOT NULL,
    status          VARCHAR(32) NOT NULL DEFAULT 'SUGGESTED',
    score           DECIMAL(8, 2) NOT NULL DEFAULT 0,
    rule_trace      VARCHAR(4000),
    reason          VARCHAR(512),
    deleted         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(128),
    updated_by      VARCHAR(128),
    version         INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_assignment_student FOREIGN KEY (student_id) REFERENCES student (id),
    CONSTRAINT fk_assignment_professor FOREIGN KEY (professor_id) REFERENCES professor (id),
    CONSTRAINT fk_assignment_university FOREIGN KEY (university_id) REFERENCES university (id)
);

CREATE INDEX idx_review_assignment_student_status ON review_assignment (student_id, status);
